export const UPDATE_DATE_DAYS_REQUEST = 'UPDATE_DATE_DAYS_REQUEST'
export const UPDATE_DATE_DAYS_SUCCESS = 'UPDATE_DATE_DAYS_SUCCESS'
export const UPDATE_DATE_DAYS_FAIL = 'UPDATE_DATE_DAYS_FAIL'

export const GET_DATE_DAYS_REQUEST = 'GET_DATE_DAYS_REQUEST' 
export const GET_DATE_DAYS_SUCCESS = 'GET_DATE_DAYS_SUCCESS'
export const GET_DATE_DAYS_FAIL = 'GET_DATE_DAYS_FAIL'