export const SUBMIT_SHIFTS_REQUEST= 'SUBMIT_SHIFTS_REQUEST';
export const SUBMIT_SHIFTS_SUCCESS= 'SUBMIT_SHIFTS_SUCCESS';
export const SUBMIT_SHIFTS_FAIL= 'SUBMIT_SHIFTS_FAIL';

export const UPDATE_SUBMITTED_SHIFTS_REQUEST= 'UPDATE_SUBMITTED_SHIFTS_REQUEST';
export const UPDATE_SUBMITTED_SHIFTS_SUCCESS= 'UPDATE_SUBMITTED_SHIFTS_SUCCESS';
export const UPDATE_SUBMITTED_SHIFTS_FAIL= 'UPDATE_SUBMITTED_SHIFTS_FAIL';