export const POST_WORKER_TEAMS_REQUEST = 'POST_WORKER_TEAMS_REQUEST'
export const POST_WORKER_TEAMS_SUCCESS = 'POST_WORKER_TEAMS_SUCCESS'
export const POST_WORKER_TEAMS_FAIL = 'POST_WORKER_TEAMS_FAIL'

export const UPDATE_WORKER_TEAMS = 'UPDATE_WORKER_TEAMS'